### ISSUE TITLE
Font Size Unusual For Large Displays

### ISSUE THREAD

**Issue by ewalfish** [salsify/kronos#2]
For large horizontal displays the UI is a bit challenging.  Can you make some CSS adjustments to make this scale a little better for that orientation.

**Comment by emoulson** [comment]
@ewalfish I made some changes to font scaling and added the long month name to make dates more readable in https://github.com/salsify/kronos/commit/c75bfe9e4c854d2ea40875ae918f1488acff0fe7. 

Let me know if that looks better.

**Comment by emoulson** [comment]
Trimmed the padding between rows and slightly decreased the size of the output times.
